In [2]:
import numpy as np


### Question 1

Given the following numpy array:

arr = np.array([1, 2, 3, 4, 5])

Write a Python code to multiply each element in the array by 2.



In [10]:
# Answer for Question 1
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr
arr=arr * 2
arr



array([ 2,  4,  6,  8, 10])

### Question 2

Given the following 2D numpy array:


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


Write a Python code to select the second row of the array.



In [14]:
# Answer for Question 2
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# return the second row
arr[1,:]

array([4, 5, 6])

### Question 3

Create a 2D numpy array of shape (5, 5) filled with the number 1.

In [17]:
# Answer for Question 3
import numpy as np
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Question 4

Given the following 2D numpy array:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


Write a Python code to calculate the sum of all the elements in each row.

In [19]:
#Answer for Question 4
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
row_sums = np.sum(arr, axis=1)
row_sums

array([ 6, 15, 24])

### Question 5

Given the following 2D numpy array:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Write a Python code to calculate the average of all the elements.

In [22]:
# Answer for Question 5 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr 



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
average = np.mean(arr)
average

np.float64(5.0)